### ISSUE TITLE
Add OpenG File Library (and others) as required package for the toolkit

### ISSUE THREAD

**Issue by kosist** [alexander-khodarev/DVR-helper#4]
VIPM build configuration allows to specify package dependencies - so when toolkit is installed, VIPM could offer to install dependencies if they are missing.
Now it seems, that main required package for this toolkit is OpenG File Library (which has in its turn other dependencies).
I've installed DVR Helper toolkit, but didn't have OpenG File Library installed. As the result - DVR Helper toolkit didn't work properly, because VIs from OpenG File Library were missing.
So it would be nice to specify in build configuration all the required dependencies, so they could be installed along with DVR Helper toolkit.

**Comment by alexander-khodarev** [comment]
@kosist - dependencies added
